---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  options:
    vvv: True
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
